"""3 tables

Revision ID: 75a3c4eaa514
Revises: 
Create Date: 2021-03-07 20:42:50.638560

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '75a3c4eaa514'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('header', sa.String(), nullable=False),
                    sa.Column('description', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('users',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('login', sa.String(), nullable=True),
                    sa.Column('password', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('login')
                    )
    op.create_table('answers',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('text', sa.String(), nullable=True),
                    sa.Column('qid', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['qid'], ['questions.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answers')
    op.drop_table('users')
    op.drop_table('questions')
    # ### end Alembic commands ###
