"""added association

Revision ID: e5e1b5fb3362
Revises: 92e1acb54831
Create Date: 2021-03-13 12:25:04.989857

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'e5e1b5fb3362'
down_revision = '92e1acb54831'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('association')
    op.drop_table('category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    categories = op.create_table('category',
                                 sa.Column('id', sa.INTEGER(), nullable=False),
                                 sa.Column('name', sa.VARCHAR(), nullable=False),
                                 sa.PrimaryKeyConstraint('id')
                                 )
    op.create_table('association',
                    sa.Column('question', sa.INTEGER(), nullable=True),
                    sa.Column('category', sa.INTEGER(), nullable=True),
                    sa.ForeignKeyConstraint(['category'], ['category.id'], ),
                    sa.ForeignKeyConstraint(['question'], ['questions.id'], )
                    )
    op.bulk_insert(categories,
                   [
                       {'id': 1, 'name': 'Физика'},
                       {'id': 2, 'name': 'История'},
                       {'id': 3, 'name': 'Алгебра'},
                       {'id': 4, 'name': 'Геометрия'},
                       {'id': 5, 'name': 'География'},
                       {'id': 6, 'name': 'Обществознание'},
                       {'id': 7, 'name': 'Химия'},
                       {'id': 8, 'name': 'Русский язык'}
                   ]
                   )
    # ### end Alembic commands ###
